
version: '3.8'
services:
  kilms-db:
    image: mysql:8.0
    container_name: kilms_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: kilms1234
      MYSQL_DATABASE: khazanah_ilmu
      MYSQL_USER: kilms_user
      MYSQL_PASSWORD: kilms_pass
    ports:
      - "3306:3306"
      - "33060:33060"
    volumes:
      - kilms_data:/var/lib/mysql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  kilms_data:
